services:
  app_proxy:
    environment:
      APP_HOST: metrics-bitcoin-wallet-exporter_web_1
      APP_PORT: 9439
      PROXY_AUTH_WHITELIST: "/metrics"
  web:
    image: lepetitbloc/bitcoind-exporter:latest@sha256:db61ca12bf7024d8ab66ed6924186a0d6bb30f03074b55f21a8a7f99962d1dcf
    user: 1000:1000
    environment:
      rpchost: wallet-proxy
      rpcport: 80
      rpcuser: $APP_BITCOIN_RPC_USER
      rpcpassword: $APP_BITCOIN_RPC_PASS
    restart: on-failure
  # Workaround because lepetitbloc/bitcoind-exporter doesn't support multiple wallets and descriptor wallets. Intercept
  # the call from the exporter to Bitcoin Core and include the wallet name in the URL and add `keypoololdest` to the
  # response body.
  wallet-proxy:
    image: traefik:v3.3.2@sha256:e8b170343bb1ab703a956049291ef0d951867bef39839c9b0d70eebda6b2ed29
    user: 1000:1000
    volumes:
      - ${APP_DATA_DIR}/data/:/etc/traefik/
      - ${APP_DATA_DIR}/data/plugins-storage/:/plugins-storage/
    environment:
      rpchost: $APP_BITCOIN_NODE_IP
      rpcport: $APP_BITCOIN_RPC_PORT
