#!/usr/bin/env bash
set -euo pipefail

file='/etc/docker/daemon.json'

if [ -f $file ] && [ -n `jq '."metrics-addr"' "$file"` ]; then
  echo '"metrics-addr" is already set'
  exit 0
fi

echo 'Ensuring "metrics-addr" is set...'
if [ -f $file ]; then
  contents=`cat "$file"`
else
  contents="{}"
fi

echo $contents | jq '. += {"metrics-addr":"127.0.0.1:9323"}' > "$file"

echo "Restarting service 'docker'..."
systemctl restart docker
