services:
  app_proxy:
    environment:
      APP_HOST: metrics-bitcoin-exporter_web_1
      APP_PORT: 9332
      PROXY_AUTH_WHITELIST: "/metrics"
  web:
    image: jvstein/bitcoin-prometheus-exporter:v0.7.0
#    user: 1000:1000
    environment:
      BITCOIN_RPC_HOST: $APP_BITCOIN_NODE_IP
      BITCOIN_RPC_PORT: $APP_BITCOIN_RPC_PORT
      BITCOIN_RPC_USER: $APP_BITCOIN_RPC_USER
      BITCOIN_RPC_PASSWORD: $APP_BITCOIN_RPC_PASS
    restart: on-failure
