services:
  web:
    image: quay.io/prometheus/node-exporter:v1.11.1@sha256:0f422f62c15f154af8d8572b23d623aebfb10cec73a5c654d18f911f3f9df241
    user: 1000:1000
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: on-failure
    volumes:
      - '/:/host'
