services:
  web:
    image: quay.io/prometheus/node-exporter:v1.8.2@sha256:4032c6d5bfd752342c3e631c2f1de93ba6b86c41db6b167b9a35372c139e7706
    user: 1000:1000
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: on-failure
    volumes:
      - '/:/host'
